apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    runner: gunicorn-gevent
    app: target
  name: gunicorn-gevent
spec:
  replicas: 1
  selector:
    matchLabels:
      runner: gunicorn-gevent
  template:
    metadata:
      labels:
        runner: gunicorn-gevent
        app: target
    spec:
      containers:
      - command:
        - gunicorn
        - -b
        - 0.0.0.0:8000
        - -w
        - "1"
        - -k
        - gevent
        - app.simple:pong
        image: kubeup/python-wsgi-benchmark
        name: gunicorn
