apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    runner: meinheld
    app: target
  name: meinheld
spec:
  replicas: 1
  selector:
    matchLabels:
      runner: meinheld
  template:
    metadata:
      labels:
        runner: meinheld
        app: target
    spec:
      containers:
      - command:
        - meinheld_server
        - -b
        - 0.0.0.0:8000
        - --disable-logging
        - app.simple:pong
        image: kubeup/python-wsgi-benchmark
        name: meinheld
